# Site settings
title: screenplays
email: 
description: > # this means to ignore newlines until "baseurl:"
  A blog for screenplays.
baseurl: "/screenplays" # the subpath of your site, e.g. /blog/
url: "https://westurner.org" # the base hostname & protocol for your site
twitter_username: westurner
github_username:  westurner

# Build settings
markdown: kramdown
    input: GFM
